version: '3.8'

services:
  server:
    container_name: 'server-nginx'
    image: 'nginx:stable-alpine'
    ports:
      - '8000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  

  php:
    container_name: 'php-laravel'
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html:delegated
  # mysql:

  # composer:

  # artisan:

  # npm: